### ISSUE TITLE
Junit using 5.3.0-RC1

### ISSUE THREAD

**Issue by Shnitzelil** [joshka/junit-json-params#4]
JUnit 5.3.1 was released.
Please upgrade

**Comment by joshka** [comment]
Hey, I'm glad you found my little convenience project. I welcome and encourage PRs.

This is released as jars at https://github.com/joshka/junit-json-params/releases/tag/1.3.1 and is deploying to maven central right now. I'm not sure what the sync time is, but check later today / tomorrow.

**Comment by joshka** [comment]
Ugh - realized that I didn't bump this correctly. Sorry. Try 1.3.1-1 in a short while.
