### ISSUE TITLE
Generate a single parameter if type is JsonArray when using @JsonFileSource

### ISSUE THREAD

**Issue by mxandeco** [joshka/junit-json-params#53]
When using `@JsonFileSource` if the file contains an array of object the argument provider will always generate a stream with individual json objects and the test will be executed once per element, that's is fine and useful, but a common is to have the actual json array, e.g.

```java
@ParameterizedTest
@JsonFileSource(resources = "/array-of-objects.json")
void jsonArray(JsonArray jsonArray  ) {
}
```

In the base above, I would like to have access to the full json object and not to each item in multiple iterations, another example would be:

```java
@ParameterizedTest
@JsonFileSource(resources = "/array-of-objects.json")
void jsonArray(List<JsonObject> jsonArray  ) {
}
```

Where then I would like a list with all the json elements at once instead of one element per test execution.

**Comment by joshka** [comment]
Great idea. Thanks for the PR! I will review it as soon as I can, but it generally LGTM (I have not yet run this).

**Comment by joshka** [comment]
Thanks again!
