### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by Kameecoding** [joshka/junit-json-params#92]
Readme says and provides examples of installation of version `r1` however only `r0` exists in the maven central.

**Comment by go2zo** [comment]
@Kameecoding You can use jitpack.io
[https://jitpack.io/#joshka/junit-json-params/v5.6.2-r1](https://jitpack.io/#joshka/junit-json-params/v5.6.2-r1)
```
repositories {
  maven { url 'https://jitpack.io' }
}

dependencies {
  implementation 'com.github.joshka:junit-json-params:v5.6.2-r1'
}
```

**Comment by joshka** [comment]
Thanks - I've recently bumped this after a long hiatus, and corrected the Readme.
